site_name: Documentação UnbHub
theme:
  favicon: assets/logo.svg
  logo: assets/logo.svg
  name: material
nav:
  - Início: index.md
  - Requisitos: Requisitos.md
  - Arquitetura: Arquitetura.md
  - Reuniões:
      - Reuniao X: Reunioes/Reuniao_modelo.md
  - Sprints:
      - Sprint 0: Sprints/Sprint0.md
      - Sprint 1: Sprints/Sprint1.md
      - Sprint 2: Sprints/Sprint2.md
      - Sprint 3: Sprints/Sprint3.md
      - Sprint 4: Sprints/Sprint4.md
  - Referências: Referencias.md


